const INPUT_PARAMETER = 'input';
const RANGE_PARAMETER = 'range';
const COLOR_PARAMETER = 'color';

window.INPUT_PARAMETER = INPUT_PARAMETER;
window.RANGE_PARAMETER = RANGE_PARAMETER;
window.COLOR_PARAMETER = COLOR_PARAMETER;